# Generated by Django 3.0.4 on 2020-03-12 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('bauthor', models.CharField(max_length=100)),
                ('bprice', models.IntegerField()),
                ('bdesc', models.TextField()),
                ('bimage', models.ImageField(upload_to='Pics')),
                ('bcondition', models.CharField(max_length=100)),
                ('sfname', models.CharField(max_length=100)),
                ('slname', models.CharField(max_length=100)),
                ('semail', models.CharField(max_length=100)),
                ('sphone', models.CharField(max_length=100)),
                ('sellerid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'books',
            },
        ),
    ]
