# Generated by Django 3.0.4 on 2020-03-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books4u', '0002_remove_books_sellerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvedbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('bauthor', models.CharField(max_length=100)),
                ('bprice', models.IntegerField()),
                ('bdesc', models.TextField()),
                ('bimage', models.ImageField(upload_to='Pics')),
                ('bcondition', models.CharField(max_length=100)),
                ('sfname', models.CharField(max_length=100)),
                ('slname', models.CharField(max_length=100)),
                ('semail', models.CharField(max_length=100)),
                ('sphone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'approvedbooks',
            },
        ),
    ]
